---

- name: Playbook to unconfigure interfaces and remove OSPF
  hosts: nxos
  gather_facts: false
  vars:
    ansible_connection: network_cli
  tasks:
  - name: Remove OSPF route from interface
    loop: "{{ configure_ospf }}"
    cisco.nxos.nxos_interface_ospf:
      interface: "{{ item.nxos_ospf_interface }}"
      ospf: "{{ item.nxos_ospf_number }}"
      area: "{{ item.nxos_ospf_area }}"
      state: absent

- name: Playbook to Configure interfaces for OSPF
  hosts: nxos
  gather_facts: false
  vars:
    ansible_connection: network_cli
  tasks:
  - name: CONFIGURE OSPF PROCESS ID AND AREA AND ROUTER ID
    cisco.nxos.nxos_config:
      lines:
        - 'router-id {{ router_id }}'
      parents: 'router ospf {{ ospf_process_id }}'
      before: 'no router ospf {{ ospf_process_id }}'


  - name: Create interface
    loop: "{{ configure_ospf }}"
    cisco.nxos.nxos_interfaces:
      config:
      - name: "{{ item.nxos_ospf_interface }}"
        description: "{{ item.nxos_ospf_interface }} Configured by Ansible"
        enabled: true
      state: merged

  - name: Set interface IPv4 address
    loop: "{{ configure_ospf }}"
    cisco.nxos.nxos_l3_interface:
      name: "{{ item.nxos_ospf_interface }}"
      ipv4: "{{ item.nxos_ip }}"
      state: present

  - name: Add OSPF configuration to the interface
    loop: "{{ configure_ospf }}"
    cisco.nxos.nxos_interface_ospf:
      interface: "{{ item.nxos_ospf_interface }}"
      ospf: "{{ item.nxos_ospf_number }}"
      area: "{{ item.nxos_ospf_area }}"
      state: present